PID:
  d: 0.15
  i: 0
  p: 0.44
  scale_finding_lane: 32
angle:
  scale: 1
  max: 25
controller:
  algorithm: random_forest
  turn_soon: True
detection:
  shape: !!python/tuple
  - 320
  - 320
  weight_path: './weights/detection/best_yolov5m.pt'
recognition:
  shape: !!python/tuple
  - 64
  - 64
  weight_path: './weights/recognition/cnn.pth'
  classes:
    - straight
    - turn_left
    - turn_right
    - no_turn_left
    - no_turn_right
    - no_straight
    - unknown
segmentation:
  shape: !!python/tuple
  - 160
  - 80
  weight_path: './weights/segmentation/unet_transfer.pth'
speed:
  linear_slope: -5
  max: 300
  min: 20
parameters:
  width_lane: 55.0
  show_image: False
mode:
  music: False
