PID:
  d: 0.05
  i: 0
  p: 0.43
  scale_finding_lane: 30
angle:
  scale: 1
classes:
- straight
- turn_left
- turn_right
- no_turn_left
- no_turn_right
- no_straight
- unknown
controller:
  algorithm: random_forest
detection:
  shape: !!python/tuple
  - 320
  - 320
  weight_path: './weights/detection/best_m.pt'
recognition:
  shape: !!python/tuple
  - 64
  - 64
  weight_path: './weights/recognition/weight6_sum.pth'
segmentation:
  shape: !!python/tuple
  - 160
  - 80
  weight_path: './weights/segmentation/unet_v2.pth'
speed:
  max: 110
  min: 20
