PID:
  d: 0.05
  i: 0
  p: 0.4
  scale_finding_lane: 5
angle:
  scale: 28
classes:
- straight
- turn_left
- turn_right
- no_turn_left
- no_turn_right
- no_straight
- unknown
controller:
  algorithm: random_forest
detection:
  shape: !!python/tuple
  - 320
  - 320
  weight_path: path/to/weight
recognition:
  shape: !!python/tuple
  - 64
  - 64
  weight_path: path/to/weight
segmentation:
  shape: !!python/tuple
  - 160
  - 80
  weight_path: path/to/weight
speed:
  max: 100
  min: 20
